package com.softdesign.devintensive.utils;


public interface ConstantManager {
    String TAG_PREFIX = "DEV ";

    String EDIT_MODE_KEY = "EDIT_MODE_KEY";

    String USER_PHONE_KEY = "USER_PHONE_KEY";
    String USER_EMAIL_KEY = "USER_EMAIL_KEY";
    String USER_VK_KEY = "USER_VK_KEY";
    String USER_REPO_KEY = "USER_REPO_KEY";
    String USER_ABOUT_KEY = "USER_ABOUT_KEY";
    String USER_PHOTO_KEY = "USER_PHOTO_KEY";
    String USER_AVATAR_KEY = "USER_AVATAR_KEY";
    String USER_ID_KEY = "USER_ID_KEY";
    String AUTH_TOKEN_KEY = "AUTH_TOKEN_KEY";

    String USER_RATING_VALUE = "USER_RATING_VALUE";
    String USER_CODELINES_VALUE = "USER_CODELINES_VALUE";
    String USER_PROJECTS_VALUE = "USER_PROJECTS_VALUE";

    String LAST_NAME_KEY = "LAST_NAME_KEY";
    String FIRST_NAME_KEY = "FIRST_NAME_KEY";

    int LOAD_PROFILE_PHOTO = 1;
    int REQUEST_CAMERA_PICTURE = 99;
    int REQUEST_GALLERY_PICTURE = 88;
    int PERMISSION_REQUEST_SETTINGS_CODE = 101;
    int CAMERA_REQUEST_PERMISSION_CODE = 102;
    int CALL_REQUEST_PERMISSION_CODE = 103;

    int MAKE_CALL_CODE = 201;
    int OPEN_LINK_CODE = 202;
    int SEND_MAIL_CODE = 203;
}
